# Generated by Django 5.1.3 on 2024-11-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('nao_feita', 'Não feita'), ('concluida', 'Concluída')], default='em_andamento', max_length=20),
        ),
    ]
